import { Company, CompanyType, Province } from './types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: '1',
    name: 'PT. Nusantara Indo Tex',
    type: CompanyType.TEXTILE,
    province: Province.WEST_JAVA,
    city: 'Bandung',
    capacity: '1,200,000 meters/month',
    employees: 2500,
    certifications: ['ISO 9001', 'OEKO-TEX Standard 100', 'SNI Sukarela'],
    exportMarkets: ['USA', 'Japan', 'EU'],
    specialization: 'Sustainable Denim & Cotton Twill',
    description: 'Leading textile producer focusing on eco-friendly denim production using recycled water systems.',
    contactEmail: 'sales@nusantaratex.co.id',
    phone: '6281122334455',
    verified: true,
  },
  {
    id: '2',
    name: 'PT. Solo Batik Sejahtera',
    type: CompanyType.GARMENT,
    province: Province.CENTRAL_JAVA,
    city: 'Surakarta',
    capacity: '50,000 pcs/month',
    employees: 450,
    certifications: ['SNI Wajib', 'Batikmark'],
    exportMarkets: ['Malaysia', 'Singapore', 'Domestic'],
    specialization: 'Traditional & Modern Batik Wear',
    description: 'Specializing in high-quality printed and hand-drawn batik for formal and casual wear.',
    contactEmail: 'info@solobatik.com',
    phone: '6281234567890',
    verified: true,
  },
  {
    id: '3',
    name: 'CV. Maju Apparel Indonesia',
    type: CompanyType.GARMENT,
    province: Province.CENTRAL_JAVA,
    city: 'Semarang',
    capacity: '800,000 pcs/month',
    employees: 3200,
    certifications: ['WRAP Gold', 'BSCI', 'ISO 9001'],
    exportMarkets: ['USA', 'Canada', 'Australia'],
    specialization: 'Sportswear & Activewear',
    description: 'Large scale garment manufacturer for major international sportswear brands.',
    contactEmail: 'biz@majuapparel.id',
    phone: '6281398765432',
    verified: true,
  },
  {
    id: '4',
    name: 'PT. Benang Emas Spinning',
    type: CompanyType.SPINNING,
    province: Province.WEST_JAVA,
    city: 'Purwakarta',
    capacity: '500 tons/month',
    employees: 1200,
    certifications: ['ISO 14001', 'Better Cotton Initiative', 'SNI Wajib'],
    exportMarkets: ['China', 'Bangladesh', 'Turkey'],
    specialization: 'Rayon & Polyester Blends',
    description: 'Modern spinning mill producing high-quality yarns for knitting and weaving.',
    contactEmail: 'sales@benangemas.co.id',
    phone: '6281567890123',
    verified: true,
  },
  {
    id: '5',
    name: 'PT. Bali Sarong Eksklusif',
    type: CompanyType.GARMENT,
    province: Province.BALI,
    city: 'Denpasar',
    capacity: '20,000 pcs/month',
    employees: 150,
    certifications: ['Fair Trade'],
    exportMarkets: ['Australia', 'Europe'],
    specialization: 'Resort Wear & Beach Coverups',
    description: 'Boutique garment factory specializing in handcrafted resort wear.',
    contactEmail: 'hello@balisarong.com',
    phone: '6281789012345',
    verified: false,
  },
  {
    id: '6',
    name: 'PT. Tangerang Zipper & Buttons',
    type: CompanyType.ACCESSORIES,
    province: Province.BANTEN,
    city: 'Tangerang',
    capacity: '5,000,000 units/month',
    employees: 600,
    certifications: ['ISO 9001', 'SNI Wajib'],
    exportMarkets: ['Domestic', 'Vietnam'],
    specialization: 'Metal Zippers & Polyester Buttons',
    description: 'One-stop solution for garment accessories.',
    contactEmail: 'orders@tangerangacc.co.id',
    phone: '6281890123456',
    verified: true,
  },
  {
    id: '7',
    name: 'PT. Surabaya Knitwear',
    type: CompanyType.GARMENT,
    province: Province.EAST_JAVA,
    city: 'Surabaya',
    capacity: '300,000 pcs/month',
    employees: 1500,
    certifications: ['SA8000', 'OEKO-TEX'],
    exportMarkets: ['EU', 'UK'],
    specialization: 'Knitted Sweaters & Polos',
    description: 'High-tech knitting facility capable of complex patterns and seamless garments.',
    contactEmail: 'contact@subknitwear.id',
    phone: '6281901234567',
    verified: true,
  },
  {
    id: '8',
    name: 'PT. Jakarta High Fashion',
    type: CompanyType.GARMENT,
    province: Province.DKI,
    city: 'North Jakarta',
    capacity: '100,000 pcs/month',
    employees: 800,
    certifications: ['ISO 9001'],
    exportMarkets: ['Middle East', 'Domestic'],
    specialization: 'Modest Fashion & Hijab',
    description: 'Premium manufacturer focusing on the growing modest fashion market.',
    contactEmail: 'admin@jhf.co.id',
    phone: '6281123456780',
    verified: true,
  },
  {
    id: '9',
    name: 'PT. Eco Fibers Indo',
    type: CompanyType.SPINNING,
    province: Province.CENTRAL_JAVA,
    city: 'Boyolali',
    capacity: '300 tons/month',
    employees: 900,
    certifications: ['GRS (Global Recycled Standard)', 'OEKO-TEX'],
    exportMarkets: ['Global'],
    specialization: 'Recycled Polyester Yarn',
    description: 'Pioneers in turning PET bottles into high-quality textile fibers.',
    contactEmail: 'info@ecofibers.id',
    phone: '6281234509876',
    verified: true,
  },
  {
    id: '10',
    name: 'PT. West Java Dyeing House',
    type: CompanyType.TEXTILE,
    province: Province.WEST_JAVA,
    city: 'Cimahi',
    capacity: '2,000,000 meters/month',
    employees: 1100,
    certifications: ['ZDHC Level 3', 'OEKO-TEX', 'ISO 9001'],
    exportMarkets: ['Domestic', 'ASEAN'],
    specialization: 'Fabric Dyeing & Finishing',
    description: 'State-of-the-art dyeing facility with zero liquid discharge technology.',
    contactEmail: 'service@wjdh.co.id',
    phone: '6281345678901',
    verified: true,
  },
  {
    id: '11',
    name: 'PT. Kahatex Modern',
    type: CompanyType.TEXTILE,
    province: Province.WEST_JAVA,
    city: 'Sumedang',
    capacity: '3,500,000 meters/month',
    employees: 15000,
    certifications: ['ISO 9001', 'ISO 14001', 'OEKO-TEX', 'SNI Wajib'],
    exportMarkets: ['Global'],
    specialization: 'Integrated Textile & Garment',
    description: 'One of the largest integrated textile facilities in Southeast Asia.',
    contactEmail: 'corporate@kahatexmodern.com',
    phone: '6281567890111',
    verified: true,
  },
  {
    id: '12',
    name: 'PT. Global Garment Solusi',
    type: CompanyType.GARMENT,
    province: Province.CENTRAL_JAVA,
    city: 'Boyolali',
    capacity: '1,500,000 pcs/month',
    employees: 5000,
    certifications: ['Better Work Indonesia', 'WRAP Platinum', 'ISO 9001'],
    exportMarkets: ['USA', 'EU', 'Japan'],
    specialization: 'Technical Outerwear & Jackets',
    description: 'Specializing in waterproof and breathable outerwear for global outdoor brands.',
    contactEmail: 'sales@ggs-boyolali.id',
    phone: '6281789012222',
    verified: true,
  },
  {
    id: '13',
    name: 'PT. Sritex International',
    type: CompanyType.TEXTILE,
    province: Province.CENTRAL_JAVA,
    city: 'Sukoharjo',
    capacity: '2,000,000 meters/month',
    employees: 8000,
    certifications: ['ISO 9001', 'NATO Standard', 'SNI Sukarela'],
    exportMarkets: ['Global', 'NATO Countries'],
    specialization: 'Military Uniforms & Corporate Wear',
    description: 'World-renowned producer of military uniforms and specialized corporate clothing.',
    contactEmail: 'export@sritex-int.com',
    phone: '6281890123333',
    verified: true,
  },
  {
    id: '14',
    name: 'PT. Indo-Rama Fibers',
    type: CompanyType.SPINNING,
    province: Province.WEST_JAVA,
    city: 'Purwakarta',
    capacity: '2,000 tons/month',
    employees: 2500,
    certifications: ['OEKO-TEX', 'ISO 9001'],
    exportMarkets: ['Asia', 'Europe', 'South America'],
    specialization: 'Spun Yarns & Polyester Staple Fiber',
    description: 'High-capacity spinning mill producing premium polyester and blended yarns.',
    contactEmail: 'marketing@indorama-fibers.co.id',
    phone: '6281901234444',
    verified: true,
  },
  {
    id: '15',
    name: 'PT. Ungaran Export Apparel',
    type: CompanyType.GARMENT,
    province: Province.CENTRAL_JAVA,
    city: 'Ungaran',
    capacity: '600,000 pcs/month',
    employees: 2800,
    certifications: ['BSCI', 'Sedex', 'ISO 9001'],
    exportMarkets: ['USA', 'UK'],
    specialization: 'Ladies Blouses & Dresses',
    description: 'Focused on high-fashion ladies wear with intricate detailing and embroidery.',
    contactEmail: 'orders@ungaran-apparel.com',
    phone: '6281123456555',
    verified: true,
  },
  {
    id: '16',
    name: 'PT. Dan Liris Kreasi',
    type: CompanyType.TEXTILE,
    province: Province.CENTRAL_JAVA,
    city: 'Sukoharjo',
    capacity: '900,000 meters/month',
    employees: 3000,
    certifications: ['ISO 9001', 'ISO 14001', 'SNI Wajib'],
    exportMarkets: ['USA', 'UK', 'Australia'],
    specialization: 'Batik Printing & Cotton Fabrics',
    description: 'Heritage company combining traditional batik art with modern printing technology.',
    contactEmail: 'info@danliris-kreasi.id',
    phone: '6281234509666',
    verified: true,
  },
  {
    id: '17',
    name: 'PT. Ateja Interior Fabrics',
    type: CompanyType.TEXTILE,
    province: Province.WEST_JAVA,
    city: 'Bandung',
    capacity: '800,000 meters/month',
    employees: 1800,
    certifications: ['IMO (Fire Safety)', 'ISO 9001', 'OEKO-TEX'],
    exportMarkets: ['Global'],
    specialization: 'Upholstery & Technical Textiles',
    description: 'Premium manufacturer of fabrics for automotive, transportation, and home interior.',
    contactEmail: 'sales@ateja-interior.com',
    phone: '6281345678777',
    verified: true,
  },
  {
    id: '18',
    name: 'PT. Trisula Uniforms',
    type: CompanyType.GARMENT,
    province: Province.WEST_JAVA,
    city: 'Cimahi',
    capacity: '200,000 sets/month',
    employees: 1200,
    certifications: ['ISO 9001', 'SNI Sukarela'],
    exportMarkets: ['Japan', 'Australia', 'Domestic'],
    specialization: 'Corporate Uniforms & Workwear',
    description: 'Expert in durable and functional uniforms for airlines, banks, and government bodies.',
    contactEmail: 'b2b@trisula-uniforms.co.id',
    phone: '6281567890888',
    verified: true,
  },
  {
    id: '19',
    name: 'PT. Metro Kemeja',
    type: CompanyType.GARMENT,
    province: Province.WEST_JAVA,
    city: 'Tasikmalaya',
    capacity: '150,000 pcs/month',
    employees: 600,
    certifications: ['SNI Sukarela'],
    exportMarkets: ['Domestic', 'Malaysia'],
    specialization: 'Men\'s Formal Shirts',
    description: 'Specialist in high-quality woven shirts with embroidery capabilities.',
    contactEmail: 'info@metrokemeja.com',
    phone: '6281789012999',
    verified: false,
  },
  {
    id: '20',
    name: 'PT. Karawang Fiber Tech',
    type: CompanyType.SPINNING,
    province: Province.WEST_JAVA,
    city: 'Karawang',
    capacity: '1,200 tons/month',
    employees: 1500,
    certifications: ['ISO 50001 (Energy Mgmt)', 'ISO 9001'],
    exportMarkets: ['China', 'Korea'],
    specialization: 'Synthetic Fibers & Nylon',
    description: 'Technology-driven plant producing specialized nylon fibers for industrial use.',
    contactEmail: 'tech@karawangfiber.id',
    phone: '6281890123000',
    verified: true,
  },
  {
    id: '21',
    name: 'PT. Busana Prima',
    type: CompanyType.GARMENT,
    province: Province.WEST_JAVA,
    city: 'Bogor',
    capacity: '450,000 pcs/month',
    employees: 2000,
    certifications: ['WRAP Gold', 'OEKO-TEX'],
    exportMarkets: ['USA', 'EU'],
    specialization: 'Lingerie & Underwear',
    description: 'High-precision manufacturing for intimate apparel brands.',
    contactEmail: 'partners@busanaprima.com',
    phone: '6281901234111',
    verified: true,
  },
  {
    id: '22',
    name: 'PT. Probolinggo Denim',
    type: CompanyType.GARMENT,
    province: Province.EAST_JAVA,
    city: 'Probolinggo',
    capacity: '300,000 pcs/month',
    employees: 1800,
    certifications: ['Levi\'s Terms of Engagement', 'ISO 14001', 'SNI Wajib'],
    exportMarkets: ['USA', 'Japan'],
    specialization: 'Denim Jeans & Jackets',
    description: 'Full-service denim factory with in-house laundry and finishing.',
    contactEmail: 'wash@probolinggodenim.com',
    phone: '6281123456222',
    verified: true,
  },
  {
    id: '23',
    name: 'PT. Semarang Fabric Center',
    type: CompanyType.TEXTILE,
    province: Province.CENTRAL_JAVA,
    city: 'Semarang',
    capacity: '600,000 meters/month',
    employees: 900,
    certifications: ['OEKO-TEX'],
    exportMarkets: ['Domestic'],
    specialization: 'Rayon & Viscose Printing',
    description: 'Focusing on fast-fashion fabric printing with quick turnaround times.',
    contactEmail: 'print@semarangfabric.com',
    phone: '6281234509333',
    verified: false,
  },
  {
    id: '24',
    name: 'PT. Grand Textile Industry',
    type: CompanyType.TEXTILE,
    province: Province.WEST_JAVA,
    city: 'Bandung',
    capacity: '1,000,000 meters/month',
    employees: 2200,
    certifications: ['ISO 9001', 'Bluesign', 'SNI Sukarela'],
    exportMarkets: ['EU', 'USA'],
    specialization: 'Suiting Fabrics & Wool Blends',
    description: 'Premium wool and wool-blend fabric manufacturer for luxury suits.',
    contactEmail: 'sales@grandtextile.co.id',
    phone: '6281345678444',
    verified: true,
  },
  {
    id: '25',
    name: 'PT. Aksesoris Garmen Indonesia',
    type: CompanyType.ACCESSORIES,
    province: Province.DKI,
    city: 'West Jakarta',
    capacity: '10,000,000 units/month',
    employees: 300,
    certifications: ['ISO 9001', 'SNI Sukarela'],
    exportMarkets: ['Domestic', 'ASEAN'],
    specialization: 'Labels, Tags & Packaging',
    description: 'Complete branding solutions including woven labels, hangtags, and polybags.',
    contactEmail: 'order@agi-accessories.com',
    phone: '6281567890555',
    verified: true,
  }
];